# Generated by Django 3.0.2 on 2020-01-17 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAdministrador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idCarrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarrera', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('usuarioCliente', models.CharField(max_length=100)),
                ('passwordCliente', models.CharField(max_length=100)),
                ('estadoCliente', models.IntegerField(default=0)),
                ('correoCliente', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('idMateria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMateria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('idTermino', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTermino', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=100)),
                ('apellidoUsuario', models.CharField(max_length=100)),
                ('correoUsuario', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('idMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcsh.Materia')),
                ('idTermino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcsh.Termino')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('idNoticia', models.AutoField(primary_key=True, serialize=False)),
                ('nombreNoticia', models.CharField(max_length=100)),
                ('descrNoticia', models.CharField(max_length=400)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcsh.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('idDescarga', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDescarga', models.DateTimeField(verbose_name='date published')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcsh.Usuario')),
            ],
        ),
    ]
